[versions]
agp = "8.13.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
room = "2.8.4"
coroutines = "1.9.0"
okhttp = "4.12.0"
graphicsPath = "1.1.0"
composeBom = "2024.10.01"
coreKtx = "1.17.0"
activityCompose = "1.11.0"
lifecycle = "2.9.4"
junit4 = "4.13.2"
truth = "1.4.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
graphics-path = { group = "androidx.graphics", name = "graphics-path", version.ref = "graphicsPath" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
